kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

services:
  - name: nats-streaming
    image: nats-streaming
    command: [-mc, 0]
    ports:
      - 4222

steps:
  - name: tests
    image: golang:1.12
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
      COVERALLS_TOKEN:
        from_secret: COVERALLS_TOKEN
    commands:
      - export STAN_HOST="nats-streaming"
      - go get -v golang.org/x/lint/golint
      - go get -v golang.org/x/tools/cmd/cover
      - go get -v github.com/mattn/goveralls
      - go get -v github.com/modocache/gover
      - go get -v github.com/nats-io/gnatsd
      - go get -v github.com/onsi/ginkgo/ginkgo
      - go get -v github.com/onsi/gomega
      - go get -v github.com/moleculer-go/cupaloy
      - go build
      - go test ./... -race -coverprofile=coverage.txt -covermode=atomic 2>&1 > /dev/null || echo "Skipping CodeCov coverage file creation"
      - ginkgo -r --randomizeAllSpecs --failFast --cover --trace
      - gover ./ coverage.txt
      - curl -s https://codecov.io/bash | bash
      - goveralls -coverprofile=coverage.txt -service=drone.io
