language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x

os:
  - linux
  - osx
  - windows

before_install:
  - go get -v golang.org/x/lint/golint
  - go get -v golang.org/x/tools/cmd/cover
  - go get -v github.com/mattn/goveralls

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && `go version | grep 1.11` ]]; then "curl https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh?$(date +%s) | sudo bash" ; fi

script:
  - go test -v ./...
  - if [[ "$TRAVIS_OS_NAME" == "linux" && `go version | grep 1.11` ]]; then $GOPATH/bin/goveralls -service=travis-ci          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && `go version | grep 1.11` ]]; then fossa init          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && `go version | grep 1.11` ]]; then fossa analyze          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && `go version | grep 1.11` ]]; then fossa test          ; fi
